import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ceveat } from "../app/utils/font";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full  lg:h-screen  lg:place-content-center relative  overflow-x-hidden`}
      >
        <div className="flex flex-col lg:flex-row w-full  gap-10  px-3  py-5 lg:w-[90%] mx-auto lg:!min-h-[80%]">
          <div className=" flex-1 w-full lg:max-w-[350px] rounded-xl h-fit  z-50">
            <Sidebar />
          </div>
          <div className="flex-1 lg:flex-2  bg-eerie-black-2  rounded-xl border-purple  z-50 overflow-hidden  ">
            <div className="hidden lg:block">
              <Navbar />
            </div>
            {children}
          </div>
        </div>
        <div className="block lg:hidden">
          <Navbar />
        </div>
        <div className="absolute right-[100px] z-10 h-[150px] w-[400px] rotate-[0deg] transform rounded-full bg-gradient-to-tl from-slate-800 via-violet-500 to-zinc-400 blur-[150px] top-[-150px]"></div>
        <div className="fixed right-[100px] z-10 h-[150px] w-[400px] rotate-[0deg] transform rounded-full bg-gradient-to-tl from-slate-800 via-violet-600 to-zinc-400 blur-[50px] top-[-150px]"></div>
        <div className=" dotted-background h-full top-0 left-0 right-0 ">
          <div className="absolute left-0 right-0 bottom-0 h-[300px]"></div>
        </div>
      </body>
    </html>
  );
}
